### ISSUE TITLE
爬取文档失败，是个人知识库。报错信息如下，忘解答，感谢！

### ISSUE THREAD

**Issue by AngevolShady** [burpheart/yuque-crawl#10]
Traceback (most recent call last):
  File "/Users/liyidan/Downloads/yuque-crawl-main/main.py", line 98, in <module>
    get_book()
  File "/Users/liyidan/Downloads/yuque-crawl-main/main.py", line 45, in get_book
    if (os.path.exists("download/" + str(docsjson['book']['id'])) == False):
                                         ~~~~~~~~^^^^^^^^
KeyError: 'book'

**Comment by Txy-Sky** [comment]
我也是，现在有解决办法吗
