### ISSUE TITLE
再下载部分文档的时候提示以下报错

### ISSUE THREAD

**Issue by sh1yan** [burpheart/yuque-crawl#4]
部分收藏库提示以下报错信息：
`E:\yuque-crawl>python3 main.py https://www.yuque.com/aceld/lfhu8y
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    get_book(sys.argv[1])
  File "main.py", line 65, in get_book
    if (temp[doc['parent_uuid']].endswith("/")):
KeyError: 'uPPZE7JwsEFElXBW'
`

**Comment by burpheart** [comment]
因为语雀允许使用文档作为文档的父级目录使用
遍历出来的目录列表里面不包含文档
目前还没有写这个特殊处理

**Comment by nnnmdzz** [comment]
是因为文档作为父目录的时候type是doc，所以要做进一步判断，可以将temp赋值前的条件
```python
if doc['type'] == 'TITLE'
```
修改为
```python
if doc['type'] == 'TITLE' or doc['child_uuid'] != '':
```
