### ISSUE TITLE
部分文档执行失败

### ISSUE THREAD

**Issue by Cinta-i29** [burpheart/yuque-crawl#8]
如图

"
Traceback (most recent call last):
  File "E:\app\语雀爬虫\yuque-crawl\main.py", line 90, in <module>
    get_book()
  File "E:\app\语雀爬虫\yuque-crawl\main.py", line 38, in get_book
    if (os.path.exists("download/" + str(docsjson['book']['id'])) == False):
                                         ~~~~~~~~^^^^^^^^
KeyError: 'book'
"


<img width="978" alt="20231221211546" src="https://github.com/burpheart/yuque-crawl/assets/126969921/fa5f9fd7-e347-47e9-8928-89644a3735f6">

**Comment by taozhenhuanx** [comment]
这应该是别人的加密仓库，只有可阅读权限

**Comment by bytes-code** [comment]
有什么方法可以对加密仓库进行数据读取吗，或者需要别人放开什么权限
